name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare pnpm
        uses: pnpm/action-setup@v4

      - name: Prepare Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: ESLint
        run: pnpm run eslint

      - name: Prettier code style check
        run: pnpm prettier . --check

      - name: Build
        run: pnpm run build
